/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/btxRiZl0m4V
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Blog() {
  return (
    <>
      <main className="flex-1 bg-gray-100 py-8 px-6 md:px-12">
        <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="col-span-2">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <img
                  alt="Blog Post Image"
                  className="rounded-lg object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <h2 className="text-2xl font-bold mt-4">Unlocking the Secrets of Gut Health</h2>
                <p className="text-gray-600 mt-2">
                  Discover the latest research on how to optimize your gut health for better overall wellness.
                </p>
                <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                  Read More
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
              </div>
              <div>
                <img
                  alt="Blog Post Image"
                  className="rounded-lg object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <h2 className="text-2xl font-bold mt-4">The Surprising Benefits of Meditation</h2>
                <p className="text-gray-600 mt-2">
                  Explore the science-backed advantages of incorporating meditation into your daily routine.
                </p>
                <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                  Read More
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
              </div>
              <div>
                <img
                  alt="Blog Post Image"
                  className="rounded-lg object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <h2 className="text-2xl font-bold mt-4">The Future of Personalized Medicine</h2>
                <p className="text-gray-600 mt-2">
                  Learn how advancements in genomics and data science are transforming the way we approach healthcare.
                </p>
                <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                  Read More
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
              </div>
              <div>
                <img
                  alt="Blog Post Image"
                  className="rounded-lg object-cover"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
                <h2 className="text-2xl font-bold mt-4">The Importance of Sleep for Optimal Health</h2>
                <p className="text-gray-600 mt-2">
                  Explore the latest research on the critical role of sleep in maintaining physical and mental
                  well-being.
                </p>
                <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                  Read More
                  <ArrowRightIcon className="ml-2 h-5 w-5" />
                </Link>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md p-6">
            <h3 className="text-xl font-bold mb-4">Popular Categories</h3>
            <ul className="space-y-2">
              <li>
                <Link className="text-blue-600 hover:text-blue-800" href="#">
                  Health Tips
                </Link>
              </li>
              <li>
                <Link className="text-blue-600 hover:text-blue-800" href="#">
                  Medical Research
                </Link>
              </li>
              <li>
                <Link className="text-blue-600 hover:text-blue-800" href="#">
                  Wellness
                </Link>
              </li>
              <li>
                <Link className="text-blue-600 hover:text-blue-800" href="#">
                  Treatments
                </Link>
              </li>
            </ul>
            <div className="mt-8">
              <h3 className="text-xl font-bold mb-4">Search</h3>
              <form>
                <div className="relative">
                  <SearchIcon className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                  <Input
                    className="w-full bg-gray-100 rounded-md pl-10 pr-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Search blog posts"
                    type="text"
                  />
                </div>
              </form>
            </div>
            <div className="mt-8">
              <h3 className="text-xl font-bold mb-4">Newsletter</h3>
              <form>
                <div className="relative">
                  <Input
                    className="w-full bg-gray-100 rounded-md pr-4 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter your email"
                    type="email"
                  />
                  <Button className="absolute right-2 top-1/2 transform -translate-y-1/2" type="submit">
                    Subscribe
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
      <section className="bg-gray-100 py-12 px-6 md:px-12">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold mb-8">Featured Articles</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <img
                alt="Featured Article Image"
                className="rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <h3 className="text-2xl font-bold mt-4">The Power of Mindfulness</h3>
              <p className="text-gray-600 mt-2">
                Discover how mindfulness can transform your mental and physical well-being.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Featured Article Image"
                className="rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <h3 className="text-2xl font-bold mt-4">Nutrition for Optimal Aging</h3>
              <p className="text-gray-600 mt-2">Learn how to fuel your body for a longer, healthier life.</p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Featured Article Image"
                className="rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <h3 className="text-2xl font-bold mt-4">The Rise of Telemedicine</h3>
              <p className="text-gray-600 mt-2">
                Explore how virtual healthcare is transforming the patient experience.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-white py-12 px-6 md:px-12">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold mb-8">Latest Research</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <img
                alt="Latest Research Image"
                className="rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <h3 className="text-2xl font-bold mt-4">Breakthrough in Cancer Treatment</h3>
              <p className="text-gray-600 mt-2">
                Discover the latest advancements in cancer research and treatment options.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Latest Research Image"
                className="rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <h3 className="text-2xl font-bold mt-4">The Gut-Brain Connection</h3>
              <p className="text-gray-600 mt-2">
                Explore the latest research on the powerful link between gut health and brain function.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-gray-100 py-12 px-6 md:px-12">
        <div className="container mx-auto">
          <h2 className="text-3xl font-bold mb-8">Trending Topics</h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <img
                alt="Trending Topic Image"
                className="rounded-lg object-cover"
                height={200}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-4">The Benefits of Yoga</h3>
              <p className="text-gray-600 mt-2">
                Discover how this ancient practice can improve your physical and mental well-being.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Trending Topic Image"
                className="rounded-lg object-cover"
                height={200}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-4">The Future of Wearable Tech</h3>
              <p className="text-gray-600 mt-2">
                Explore how wearable devices are transforming the way we monitor and manage our health.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Trending Topic Image"
                className="rounded-lg object-cover"
                height={200}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-4">The Rise of Telehealth</h3>
              <p className="text-gray-600 mt-2">
                Learn how virtual healthcare is improving access and convenience for patients.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
            <div>
              <img
                alt="Trending Topic Image"
                className="rounded-lg object-cover"
                height={200}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-4">The Importance of Sleep</h3>
              <p className="text-gray-600 mt-2">
                Discover the latest research on the critical role of sleep in maintaining optimal health.
              </p>
              <Link className="inline-flex items-center mt-4 text-blue-600 hover:text-blue-800" href="#">
                Read More
                <ArrowRightIcon className="ml-2 h-5 w-5" />
              </Link>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
