/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FhQhzMjtMTM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export default function contactus() {
  return (
    <>
      <section className="relative w-full py-12 md:py-24 lg:py-32 xl:py-48">
        <div className="absolute inset-0 " />
        <img
          alt="Background Image"
          className="absolute inset-0 h-full w-full object-cover"
          height="1080"
          src="/placeholder.svg"
          style={{
            aspectRatio: "1920/1080",
            objectFit: "cover",
          }}
          width="1920"
        />
        <div className="relative container px-4 md:px-6">
          <div className="flex flex-col items-center space-y-4 text-center">
            <div className="space-y-2 relative z-10">
              <h1 className="text-3xl font-bold tracking-tighter text-black sm:text-4xl md:text-5xl lg:text-6xl/none">
                Connect with Docdial
              </h1>
              <p className="mx-auto max-w-[700px] text-black md:text-xl">
                Get in touch with our team to learn more about our services and how we can help you find the right
                healthcare provider.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid grid-cols-1 gap-6 px-4 md:grid-cols-3 md:px-6">
          <div className="col-span-1 md:col-span-2">
            <Card className="shadow-lg">
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label className="text-black" htmlFor="name">
                    Name
                  </Label>
                  <Input
                    className="bg-gray-800 text-white placeholder:text-gray-400 focus:ring-gray-500"
                    id="name"
                    placeholder="Enter your name"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-black" htmlFor="email">
                    Email
                  </Label>
                  <Input
                    className="bg-gray-800 text-white placeholder:text-gray-400 focus:ring-gray-500"
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-black" htmlFor="phone">
                    Phone
                  </Label>
                  <Input
                    className="bg-gray-800 text-white placeholder:text-gray-400 focus:ring-gray-500"
                    id="phone"
                    placeholder="Enter your phone number"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-black" htmlFor="message">
                    Message
                  </Label>
                  <Textarea
                    className="bg-gray-800 text-white placeholder:text-gray-400 focus:ring-gray-500 min-h-[100px]"
                    id="message"
                    placeholder="Enter your message"
                  />
                </div>
                <Button className="bg-gray-900 hover:bg-gray-800 text-white" type="submit">
                  Submit
                </Button>
              </CardContent>
            </Card>
          </div>
          <div className="col-span-1 space-y-6">
            <Card className="shadow-lg">
              <CardContent>
                <img
                  alt="Map"
                  className="rounded-md"
                  height="300"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "400/300",
                    objectFit: "cover",
                  }}
                  width="400"
                />
              </CardContent>
            </Card>
            <Card className="shadow-lg">
              <CardContent className="space-y-2">
                <div className="space-y-1">
                  <h3 className="text-lg font-semibold text-white">Contact Information</h3>
                  <p className="text-gray-400">Get in touch with us for more information.</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium text-white">Address</p>
                  <p className="text-gray-400">123 Main Street, Anytown USA</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium text-white">Phone</p>
                  <p className="text-gray-400">(123) 456-7890</p>
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium text-white">Email</p>
                  <p className="text-gray-400">info@docdial.com</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </>
  )
}
